---
vector_version: "0.41.1"

# Path
vector_config_path: "/etc/vector"
vector_service_path: "/etc/systemd/system"
# Templates
vector_config_file: "vector.toml.j2"
vector_service_file: "vector.service.j2"